### ISSUE TITLE
i get this error when i import hijri-converter 

### ISSUE THREAD

**Issue by MosabAwadexp** [dralshehri/hijri-converter#1]
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.5/dist-packages/hijri_converter/convert.py", line 36
    return f"{class_name}({self._year}, {self._month}, {self._day})"

**Comment by dralshehri** [comment]
From your traceback it appears that you're using Python 3.5 which is not supported by this package. You need to upgrade your Python to version 3.6 or later.

**Comment by MosabAwadexp** [comment]
ok, i just installed python3.6 and tried to install the converter again and i got this:
root@motaz-server:~# pip3 install -U hijri-converter
Traceback (most recent call last):
  File "/usr/bin/pip3", line 11, in <module>
    sys.exit(main())
  File "/usr/lib/python3/dist-packages/pip/__init__.py", line 215, in main
    locale.setlocale(locale.LC_ALL, '')
  File "/usr/lib/python3.5/locale.py", line 594, in setlocale
    return _setlocale(category, locale)
locale.Error: unsupported locale setting

**Comment by dralshehri** [comment]
Sorry, can't help with that as it's not related to hijri-converter. I suggest to ask on https://stackoverflow.com/ where you may find an answer.
